version: "3.9"

networks:
  parent-net:
    driver: bridge

services:

  # ---------- Zookeeper ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - parent-net

  # ---------- Kafka ----------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - parent-net

  # ---------- Redis ----------
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - parent-net

  # ---------- Auth DB ----------
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    networks:
      - parent-net

  auth-service:
    build: ./AuthService
    container_name: auth-service
    depends_on:
      - auth-db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION_MS: ${JWT_ACCESS_EXP}
      JWT_REFRESH_EXPIRATION_MS: ${JWT_REFRESH_EXP}
    networks:
      - parent-net

  # ---------- User DB ----------
  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: useridb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    networks:
      - parent-net

  user-service:
    build: ./UserService
    container_name: user-service
    depends_on:
      - user-db
      - redis
      - auth-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/useridb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - parent-net

  # ---------- Order DB ----------
  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_DB: orderidb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    networks:
      - parent-net

  order-service:
    build: ./OrderService
    container_name: order-service
    depends_on:
      - order-db
      - user-service
      - auth-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderidb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      USER_SERVICE_BASE_URL: http://user-service:8082
      AUTH_SERVICE_URL: http://auth-service:8081
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - parent-net

  # ---------- Payment DB ----------
  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_DB: paymentsidb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - payment_pgdata:/var/lib/postgresql/data
    networks:
      - parent-net

  payment-service:
    build: ./PaymentService
    container_name: payment-service
    depends_on:
      - payment-db
      - kafka
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/paymentsidb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      USER_SERVICE_BASE_URL: http://user-service:8082
      ORDER_SERVICE_BASE_URL: http://order-service:8083
      API_BASE_URL: https://www.randomnumberapi.com
      API_PATH: /api/v1.0/random
      API_QUERY: ?min=1&max=100&count=1
    networks:
      - parent-net

  # ---------- API Gateway ----------
  api-gateway:
    build: ./ApiGateway
    container_name: api-gateway
    depends_on:
      - auth-service
      - user-service
      - order-service
      - payment-service
      - redis
    ports:
      - "8080:8080"
    environment:
      gateway.base: http://api-gateway:8080
      SPRING_PROFILES_ACTIVE: docker
      AUTH_SERVICE_URL: http://auth-service:8081
      USER_SERVICE_URL: http://user-service:8082
      ORDER_SERVICE_URL: http://order-service:8083
      PAYMENT_SERVICE_URL: http://payment-service:8084
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - parent-net

volumes:
  auth_pgdata:
  user_pgdata:
  order_pgdata:
  payment_pgdata: