apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  user: postgres
  password: Spa14062004
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  JWT_SECRET: wX9gR3HqKf2ZtL8QvB1yM4sJ6dN7pV0rU2xC5fT8kL3q
